"""
Curated dataset of brand-new, unlocked smartphones above £300 in the UK (March 2026).
Sources: Samsung UK, Apple UK, OnePlus UK, Google Store UK, Currys, John Lewis, Amazon UK.
Prices reflect best available retail / promotional prices at time of compilation.
"""

PHONES = [
    # ─────────────────────────────── SAMSUNG ────────────────────────────────
    {
        "brand": "Samsung",
        "model": "Galaxy S25 Ultra",
        "price_gbp": 1249,
        "original_price_gbp": 1299,
        "deal_note": "£50 trade-in promo / launch offer",
        "display": '6.9" QHD+ Dynamic AMOLED 2X, 120 Hz',
        "processor": "Snapdragon 8 Elite (4 nm)",
        "ram_gb": 12,
        "storage_gb": 256,
        "main_camera_mp": 200,
        "battery_mah": 5000,
        "five_g": True,
        "os": "Android 15 / One UI 7",
        "highlights": ["Built-in S Pen", "7 years OS updates", "AI photo editing", "Titanium frame"],
        "rating_out_of_10": 9.5,
        "best_for": "Power users & productivity",
        "unlocked": True,
        "condition": "Brand New",
        "retailers": ["samsung.com/uk", "currys.co.uk", "johnlewis.com", "amazon.co.uk"],
    },
    {
        "brand": "Samsung",
        "model": "Galaxy S25+",
        "price_gbp": 949,
        "original_price_gbp": 999,
        "deal_note": "£50 launch promo at Samsung UK",
        "display": '6.7" FHD+ Dynamic AMOLED 2X, 120 Hz',
        "processor": "Snapdragon 8 Elite (4 nm)",
        "ram_gb": 12,
        "storage_gb": 256,
        "main_camera_mp": 50,
        "battery_mah": 4900,
        "five_g": True,
        "os": "Android 15 / One UI 7",
        "highlights": ["Slimmer design", "7 years OS updates", "Vapour cooling chamber", "Bright 2600-nit display"],
        "rating_out_of_10": 9.0,
        "best_for": "Big-screen flagship without Ultra price",
        "unlocked": True,
        "condition": "Brand New",
        "retailers": ["samsung.com/uk", "currys.co.uk", "johnlewis.com"],
    },
    {
        "brand": "Samsung",
        "model": "Galaxy S25",
        "price_gbp": 749,
        "original_price_gbp": 799,
        "deal_note": "£50 off via Samsung online promo",
        "display": '6.2" FHD+ Dynamic AMOLED 2X, 120 Hz',
        "processor": "Snapdragon 8 Elite (4 nm)",
        "ram_gb": 12,
        "storage_gb": 128,
        "main_camera_mp": 50,
        "battery_mah": 4000,
        "five_g": True,
        "os": "Android 15 / One UI 7",
        "highlights": ["Compact flagship", "7 years OS updates", "Galaxy AI", "Bright display"],
        "rating_out_of_10": 8.7,
        "best_for": "Compact flagship users",
        "unlocked": True,
        "condition": "Brand New",
        "retailers": ["samsung.com/uk", "currys.co.uk", "johnlewis.com", "amazon.co.uk"],
    },
    {
        "brand": "Samsung",
        "model": "Galaxy S24 FE",
        "price_gbp": 469,
        "original_price_gbp": 499,
        "deal_note": "Frequent discounts at Currys & Amazon",
        "display": '6.7" FHD+ Dynamic AMOLED, 120 Hz',
        "processor": "Exynos 2500 (3 nm)",
        "ram_gb": 8,
        "storage_gb": 128,
        "main_camera_mp": 50,
        "battery_mah": 4700,
        "five_g": True,
        "os": "Android 15 / One UI 7",
        "highlights": ["Fan Edition value", "7 years OS updates", "Large display", "Good battery life"],
        "rating_out_of_10": 8.0,
        "best_for": "Best Samsung value under £500",
        "unlocked": True,
        "condition": "Brand New",
        "retailers": ["samsung.com/uk", "currys.co.uk", "amazon.co.uk"],
    },
    {
        "brand": "Samsung",
        "model": "Galaxy A55 5G",
        "price_gbp": 389,
        "original_price_gbp": 449,
        "deal_note": "Regular promotions; often £380–£410",
        "display": '6.6" FHD+ Super AMOLED, 120 Hz',
        "processor": "Exynos 1480 (4 nm)",
        "ram_gb": 8,
        "storage_gb": 128,
        "main_camera_mp": 50,
        "battery_mah": 5000,
        "five_g": True,
        "os": "Android 15 / One UI 7",
        "highlights": ["IP67 rated", "4 years OS updates", "OIS camera", "Gorilla Glass Victus+"],
        "rating_out_of_10": 7.8,
        "best_for": "Mid-range Samsung with premium build",
        "unlocked": True,
        "condition": "Brand New",
        "retailers": ["samsung.com/uk", "currys.co.uk", "amazon.co.uk"],
    },

    # ─────────────────────────────── APPLE ──────────────────────────────────
    {
        "brand": "Apple",
        "model": "iPhone 16 Pro Max",
        "price_gbp": 1199,
        "original_price_gbp": 1199,
        "deal_note": "No current cashback; best deal is £1,149 refurb from Apple",
        "display": '6.9" Super Retina XDR OLED ProMotion 120 Hz',
        "processor": "Apple A18 Pro (3 nm)",
        "ram_gb": 8,
        "storage_gb": 256,
        "main_camera_mp": 48,
        "battery_mah": 4685,
        "five_g": True,
        "os": "iOS 18",
        "highlights": ["5× optical zoom", "Titanium frame", "Action Button", "Apple Intelligence AI", "ProRes 4K120"],
        "rating_out_of_10": 9.5,
        "best_for": "Best iPhone overall / camera enthusiasts",
        "unlocked": True,
        "condition": "Brand New",
        "retailers": ["apple.com/uk", "currys.co.uk", "johnlewis.com", "amazon.co.uk"],
    },
    {
        "brand": "Apple",
        "model": "iPhone 16 Pro",
        "price_gbp": 999,
        "original_price_gbp": 999,
        "deal_note": "Apple trade-in up to £280; Currys occasional bundles",
        "display": '6.3" Super Retina XDR OLED ProMotion 120 Hz',
        "processor": "Apple A18 Pro (3 nm)",
        "ram_gb": 8,
        "storage_gb": 128,
        "main_camera_mp": 48,
        "battery_mah": 3582,
        "five_g": True,
        "os": "iOS 18",
        "highlights": ["5× optical zoom", "Titanium frame", "Apple Intelligence AI", "Action Button"],
        "rating_out_of_10": 9.2,
        "best_for": "Premium iPhone without the plus-size",
        "unlocked": True,
        "condition": "Brand New",
        "retailers": ["apple.com/uk", "currys.co.uk", "johnlewis.com"],
    },
    {
        "brand": "Apple",
        "model": "iPhone 16",
        "price_gbp": 799,
        "original_price_gbp": 799,
        "deal_note": "Apple trade-in up to £190; Sim-free deals on Amazon",
        "display": '6.1" Super Retina XDR OLED 60 Hz',
        "processor": "Apple A18 (3 nm)",
        "ram_gb": 8,
        "storage_gb": 128,
        "main_camera_mp": 48,
        "battery_mah": 3561,
        "five_g": True,
        "os": "iOS 18",
        "highlights": ["Apple Intelligence AI", "Action Button", "Camera Control button", "USB-C"],
        "rating_out_of_10": 8.5,
        "best_for": "Entry-level flagship iPhone",
        "unlocked": True,
        "condition": "Brand New",
        "retailers": ["apple.com/uk", "currys.co.uk", "amazon.co.uk"],
    },
    {
        "brand": "Apple",
        "model": "iPhone 15",
        "price_gbp": 679,
        "original_price_gbp": 799,
        "deal_note": "Still available new; often £629–£679 online",
        "display": '6.1" Super Retina XDR OLED 60 Hz',
        "processor": "Apple A16 Bionic (4 nm)",
        "ram_gb": 6,
        "storage_gb": 128,
        "main_camera_mp": 48,
        "battery_mah": 3349,
        "five_g": True,
        "os": "iOS 18",
        "highlights": ["USB-C port", "Dynamic Island", "Apple Intelligence AI (via upgrade)", "A16 chip"],
        "rating_out_of_10": 8.0,
        "best_for": "Saving £120 vs iPhone 16 with similar camera",
        "unlocked": True,
        "condition": "Brand New",
        "retailers": ["apple.com/uk", "amazon.co.uk", "johnlewis.com"],
    },

    # ─────────────────────────────── OnePlus ────────────────────────────────
    {
        "brand": "OnePlus",
        "model": "OnePlus 13",
        "price_gbp": 849,
        "original_price_gbp": 899,
        "deal_note": "Launch discount; £849 at OnePlus UK / Amazon",
        "display": '6.82" QHD+ LTPO AMOLED, 1–120 Hz',
        "processor": "Snapdragon 8 Elite (4 nm)",
        "ram_gb": 12,
        "storage_gb": 256,
        "main_camera_mp": 50,
        "battery_mah": 6000,
        "five_g": True,
        "os": "Android 15 / OxygenOS 15",
        "highlights": ["6000 mAh battery", "100W SuperVOOC charging", "Hasselblad tuned cameras", "IP65"],
        "rating_out_of_10": 9.1,
        "best_for": "Best battery life flagship",
        "unlocked": True,
        "condition": "Brand New",
        "retailers": ["oneplus.com/uk", "amazon.co.uk"],
    },
    {
        "brand": "OnePlus",
        "model": "OnePlus 12",
        "price_gbp": 579,
        "original_price_gbp": 649,
        "deal_note": "Price-dropped since OnePlus 13 launch; ~£579 Amazon",
        "display": '6.82" QHD+ LTPO AMOLED, 1–120 Hz',
        "processor": "Snapdragon 8 Gen 3 (4 nm)",
        "ram_gb": 12,
        "storage_gb": 256,
        "main_camera_mp": 50,
        "battery_mah": 5400,
        "five_g": True,
        "os": "Android 15 / OxygenOS 15",
        "highlights": ["5400 mAh battery", "100W wired + 50W wireless charging", "Hasselblad cameras", "IP65"],
        "rating_out_of_10": 8.8,
        "best_for": "Flagship killer – brilliant value at dropped price",
        "unlocked": True,
        "condition": "Brand New",
        "retailers": ["oneplus.com/uk", "amazon.co.uk", "currys.co.uk"],
    },
    {
        "brand": "OnePlus",
        "model": "OnePlus Nord 4",
        "price_gbp": 399,
        "original_price_gbp": 449,
        "deal_note": "Frequent deals; ~£399 Amazon / OnePlus UK",
        "display": '6.74" FHD+ AMOLED, 120 Hz',
        "processor": "Snapdragon 7+ Gen 3 (4 nm)",
        "ram_gb": 12,
        "storage_gb": 256,
        "main_camera_mp": 50,
        "battery_mah": 5500,
        "five_g": True,
        "os": "Android 14 / OxygenOS 14",
        "highlights": ["Metal unibody design", "100W wired charging", "5500 mAh battery", "OIS camera"],
        "rating_out_of_10": 8.2,
        "best_for": "Best mid-range value – spec punches above its price",
        "unlocked": True,
        "condition": "Brand New",
        "retailers": ["oneplus.com/uk", "amazon.co.uk"],
    },

    # ─────────────────────────────── Google Pixel ────────────────────────────
    {
        "brand": "Google",
        "model": "Pixel 9 Pro XL",
        "price_gbp": 1049,
        "original_price_gbp": 1099,
        "deal_note": "£50 off at Google Store; £1,049 at Currys",
        "display": '6.8" LTPO OLED, 1–120 Hz, 3000 nits',
        "processor": "Google Tensor G4 (4 nm)",
        "ram_gb": 16,
        "storage_gb": 256,  # Pixel 9 Pro XL base storage is 256 GB; Pixel 9 Pro base is 128 GB
        "rating_out_of_10": 9.3,
        "best_for": "Best Android AI experience & pure Android",
        "unlocked": True,
        "condition": "Brand New",
        "retailers": ["store.google.com/gb", "currys.co.uk", "johnlewis.com"],
    },
    {
        "brand": "Google",
        "model": "Pixel 9 Pro",
        "price_gbp": 949,
        "original_price_gbp": 999,
        "deal_note": "£50 off at Google Store; deals at Currys",
        "display": '6.3" LTPO OLED, 1–120 Hz, 3000 nits',
        "processor": "Google Tensor G4 (4 nm)",
        "ram_gb": 16,
        "storage_gb": 128,
        "main_camera_mp": 50,
        "battery_mah": 4700,
        "five_g": True,
        "os": "Android 15",
        "highlights": ["7 years OS updates", "Gemini AI", "Telephoto + macro lens", "IP68", "Compact Pro form-factor"],
        "rating_out_of_10": 9.1,
        "best_for": "Compact premium with best-in-class AI",
        "unlocked": True,
        "condition": "Brand New",
        "retailers": ["store.google.com/gb", "currys.co.uk", "johnlewis.com"],
    },
    {
        "brand": "Google",
        "model": "Pixel 9",
        "price_gbp": 749,
        "original_price_gbp": 799,
        "deal_note": "£50 off launch promo; £749 at Google Store & Currys",
        "display": '6.3" OLED, 60–120 Hz, 2700 nits',
        "processor": "Google Tensor G4 (4 nm)",
        "ram_gb": 12,
        "storage_gb": 128,
        "main_camera_mp": 50,
        "battery_mah": 4700,
        "five_g": True,
        "os": "Android 15",
        "highlights": ["7 years OS updates", "Gemini AI", "Best Night Sight camera", "IP68"],
        "rating_out_of_10": 8.8,
        "best_for": "Pure Android AI flagship at mid-flagship price",
        "unlocked": True,
        "condition": "Brand New",
        "retailers": ["store.google.com/gb", "currys.co.uk", "amazon.co.uk"],
    },
    {
        "brand": "Google",
        "model": "Pixel 8a",
        "price_gbp": 449,
        "original_price_gbp": 499,
        "deal_note": "Price-dropped since Pixel 9 launch; ~£449 Google Store",
        "display": '6.1" OLED, 60–120 Hz',
        "processor": "Google Tensor G3 (4 nm)",
        "ram_gb": 8,
        "storage_gb": 128,
        "main_camera_mp": 64,
        "battery_mah": 4492,
        "five_g": True,
        "os": "Android 15",
        "highlights": ["7 years OS updates", "Tensor G3 AI chip", "IP67", "Wireless charging", "Compact form"],
        "rating_out_of_10": 8.3,
        "best_for": "Best budget Pixel with flagship AI features",
        "unlocked": True,
        "condition": "Brand New",
        "retailers": ["store.google.com/gb", "currys.co.uk", "amazon.co.uk"],
    },
]
